services:
  postgres:
    image: postgres:17
    container_name: tlk-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - tlk_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tlk_dev -d tlk_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  tlk_postgres_data:
