[versions]
springBoot = "4.0.2"
dependencyManagement = "1.1.7"
flyway = "11.14.1"
postgres = "42.7.9"
junitBom = "5.10.0"

[libraries]
spring-boot-starter-web   = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-jdbc  = { module = "org.springframework.boot:spring-boot-starter-jdbc" }
spring-boot-starter-flyway= { module = "org.springframework.boot:spring-boot-starter-flyway" }

flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-db-postgres = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }

postgresql = { module = "org.postgresql:postgresql", version.ref = "postgres" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junitBom" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
dependency-management = { id = "io.spring.dependency-management", version.ref = "dependencyManagement" }
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway" }
